theme: solarized_dark
tab_width: 2
soft_tabs: true
line_length_guide: 80
line_wrapping: true

open_mode:
  exclusions:
    - "**/.git"

types:
  c:
    line_comment_prefix: //
  cc:
    line_comment_prefix: //
  cmake:
    line_comment_prefix: '#'
  cpp:
    line_comment_prefix: //
  cxx:
    line_comment_prefix: //
  go:
    line_comment_prefix: //
  js:
    line_comment_prefix: //
  lua:
    line_comment_prefix: --
  Makefile:
    line_comment_prefix: '#'
  py:
    line_comment_prefix: '#'
  rb:
    line_comment_prefix: '#'
  rs:
    line_comment_prefix: //
  sh:
    line_comment_prefix: '#'
  swift:
    line_comment_prefix: //
  tex:
    line_comment_prefix: '%'
  toml:
    line_comment_prefix: '#'
  yaml:
    line_comment_prefix: '#'
  yml:
    line_comment_prefix: '#'
