use commands::{Command, application, workspace, cursor, buffer, search, selection, view, git};
use input::Key;

pub fn handle(input: Key) -> Option<Command> {
    match input {
        Key::Char('q') => Some(buffer::close),
        Key::Char('F') => Some(buffer::close_others),
        Key::Char('j') | Key::Down  => Some(cursor::move_down),
        Key::Char('k') | Key::Up    => Some(cursor::move_up),
        Key::Char('h') | Key::Left  => Some(cursor::move_left),
        Key::Char('l') | Key::Right => Some(cursor::move_right),
        Key::Char('J') => Some(cursor::move_to_last_line),
        Key::Char('K') => Some(cursor::move_to_first_line),
        Key::Char('x') => Some(buffer::delete),
        Key::Char('d') => Some(buffer::delete_token),
        Key::Char(';') => Some(buffer::delete_current_line),
        Key::Char('D') => Some(buffer::delete_rest_of_line),
        Key::Char('C') => Some(buffer::change_rest_of_line),
        Key::Char('i') => Some(application::switch_to_insert_mode),
        Key::Char('s') => Some(buffer::save),
        Key::Char('H') | Key::Home => Some(cursor::move_to_start_of_line),
        Key::Char('L') | Key::End  => Some(cursor::move_to_end_of_line),
        Key::Char('b') => Some(cursor::move_to_start_of_previous_token),
        Key::Char('w') => Some(cursor::move_to_start_of_next_token),
        Key::Char('e') => Some(cursor::move_to_end_of_current_token),
        Key::Char('a') => Some(cursor::append_to_current_token),
        Key::Char('I') => Some(cursor::insert_at_first_word_of_line),
        Key::Char('A') => Some(cursor::insert_at_end_of_line),
        Key::Char('o') => Some(cursor::insert_with_newline),
        Key::Char('O') => Some(cursor::insert_with_newline_above),
        Key::Char('f') => Some(application::switch_to_second_stage_jump_mode),
        Key::Char('\'') => Some(application::switch_to_jump_mode),
        Key::Char('0') => Some(application::switch_to_command_mode),
        Key::Char(' ') => Some(application::switch_to_open_mode),
        Key::Char('v') => Some(application::switch_to_select_mode),
        Key::Char('V') => Some(application::switch_to_select_line_mode),
        Key::Char('/') => Some(application::switch_to_search_insert_mode),
        Key::Char('g') => Some(application::switch_to_line_jump_mode),
        Key::Char('t') => Some(application::switch_to_theme_mode),
        Key::Char('u') => Some(buffer::undo),
        Key::Char('r') => Some(buffer::redo),
        Key::Char('p') => Some(buffer::paste),
        Key::Char('P') => Some(buffer::paste_above),
        Key::Char('n') => Some(search::move_to_next_result),
        Key::Char('N') => Some(search::move_to_previous_result),
        Key::Char(',') | Key::PageUp   => Some(view::scroll_up),
        Key::Char('m') | Key::PageDown => Some(view::scroll_down),
        Key::Char('>') => Some(buffer::indent_line),
        Key::Char('<') => Some(buffer::outdent_line),
        Key::Char('M') => Some(buffer::merge_next_line),
        Key::Char('y') => Some(buffer::copy_current_line),
        Key::Char('c') => Some(buffer::change_token),
        Key::Char('=') => Some(git::add),
        Key::Char('R') => Some(git::copy_remote_url),
        Key::Char('z') | Key::Ctrl('z') => Some(application::suspend),
        Key::Ctrl('a') => Some(selection::select_all),
        Key::Ctrl('c') => Some(application::exit),
        Key::Char('Q') => Some(application::exit),
        Key::Ctrl('r') => Some(buffer::reload),
        Key::Char('B') => Some(workspace::new_buffer),
        Key::Tab       => Some(workspace::next_buffer),
        Key::Enter     => Some(application::switch_to_symbol_jump_mode),
        Key::Backspace => Some(buffer::backspace),
        _ => None,
    }
}
