stderr_file := "stderr"
[group('docs')]
debug:
  #!/bin/sh
  touch {{stderr_file}}
  tail_pane_id=$(tmux split-window -v -d -P -F '#{pane_id}' "tail -f {{stderr_file}}")
  docker run --rm -it -v ${PWD}/documentation:/docs wastedintel/zensical
  tmux kill-pane -t "$tail_pane_id"
