name: amp
version: git
summary: "A complete text editor for your terminal."
description: |
  Heavily inspired by Vi/Vim. Amp aims to take the core interaction model
  of Vim, simplify it, and bundle in the essential features required for
  a modern text editor.

grade: stable
confinement: classic

parts:
  amp:
    plugin: rust
    source: ./
    build-packages:
      - python
      - libxmu-dev
      - libssl-dev
      - pkg-config
      - cmake

apps:
  amp:
    command: bin/amp
